---
kind: pipeline
name: Codequality

platform:
  os: linux
  arch: amd64

steps:
- name: composer
  image: joomlaprojects/docker-images:php7.4
  commands:
  - php -v
  - composer update
  - composer require phpmd/phpmd phpstan/phpstan
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache

- name: phpcs
  image: joomlaprojects/docker-images:php7.4
  commands:
  - vendor/bin/phpcs --config-set installed_paths vendor/joomla/coding-standards
  - vendor/bin/phpcs -p --report=full --extensions=php --standard=Joomla src/

volumes:
- name: composer-cache
  host:
    path: /tmp/composer-cache

---
kind: pipeline
name: PHP 7.2

platform:
  os: linux
  arch: amd64

steps:
- name: composer
  image: joomlaprojects/docker-images:php7.2
  commands:
  - php -v
  - composer update --prefer-stable
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache

- name: PHPUnit
  image: joomlaprojects/docker-images:php7.2
  commands:
  - vendor/bin/phpunit

volumes:
- name: composer-cache
  host:
    path: /tmp/composer-cache

---
kind: pipeline
name: PHP 7.3

platform:
  os: linux
  arch: amd64

steps:
- name: composer
  image: joomlaprojects/docker-images:php7.3
  commands:
  - php -v
  - composer update --prefer-stable
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache

- name: PHPUnit
  image: joomlaprojects/docker-images:php7.3
  commands:
  - vendor/bin/phpunit

volumes:
- name: composer-cache
  host:
    path: /tmp/composer-cache

---
kind: pipeline
name: PHP 7.4

platform:
  os: linux
  arch: amd64

steps:
- name: composer
  image: joomlaprojects/docker-images:php7.4
  commands:
  - php -v
  - composer update --prefer-stable
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache

- name: PHPUnit
  image: joomlaprojects/docker-images:php7.4
  commands:
  - vendor/bin/phpunit

volumes:
- name: composer-cache
  host:
    path: /tmp/composer-cache

---
kind: pipeline
name: PHP 8.0

platform:
  os: linux
  arch: amd64

steps:
- name: composer
  image: joomlaprojects/docker-images:php8.0
  commands:
  - php -v
  - composer update --ignore-platform-reqs --prefer-stable
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache

- name: PHPUnit
  image: joomlaprojects/docker-images:php8.0
  commands:
  - vendor/bin/phpunit
  failure: ignore

volumes:
- name: composer-cache
  host:
    path: /tmp/composer-cache

---
kind: signature
hmac: 670d3c2aa160d9ab77bc4381ead0689037d9bfd2c0ca40e4019d5c1d42260f3b

...
